# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: 956021db-md-tks
  namespace: 956021db
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: tks
