# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: 956021db-md-tks
  namespace: 956021db
spec:
  template:
    spec: {}
